src/br/org/catolicasc/simples_pedidos/controller/EmpresaBean.java
package br.org.catolicasc.simples_pedidos.controller;

import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

import br.org.catolicasc.simples_pedidos.dao.EmpresaDao;
import br.org.catolicasc.simples_pedidos.entity.Empresa;

@ManagedBean
@ViewScoped
public class EmpresaBean {

	private EmpresaDao empresaDao = new EmpresaDao();
	private Empresa empresa = new Empresa();

	public void salva(Empresa empresa){
		empresaDao.salva(empresa);
		FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Empresa salvo"));
		this.empresa = new Empresa();
	}
	
	public Empresa getEmpresa(){
		return this.empresa;
	}
	
    public List<Empresa> getEmpresas(){
    	return empresaDao.listaTodos();
    }
	
	public void excluir(Empresa empresa){
		this.empresaDao.remove(empresa);
	}

	public void editar(Empresa empresa){
		this.empresa = empresa;
	}
	
	public void criar(){
		this.empresa = new Empresa();
	}
	
}

src/br/org/catolicasc/simples_pedidos/controller/EstoqueBean.java
package br.org.catolicasc.simples_pedidos.controller;

import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

import br.org.catolicasc.simples_pedidos.dao.EstoqueDao;
import br.org.catolicasc.simples_pedidos.entity.Estoque;

@ManagedBean
@ViewScoped
public class EstoqueBean {
	
	private EstoqueDao estoqueDao = new EstoqueDao();
	private Estoque estoque = new Estoque();
	
	public void salva(Estoque estoque){
		estoqueDao.salva(estoque);
		FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Estoque salvo"));
		this.estoque = new Estoque();
	}
	
	public void editar(Estoque estoque) {
		this.estoque = estoque;
	}
	
	public void criar(){
		this.estoque = new Estoque();
	}
	
	public Estoque getEstoque(){
		return this.estoque;
	}
	
	public List<Estoque> getEstoques(){
		return estoqueDao.listaTodos();
	}
	
	public void excluir(Estoque estoque){
		this.estoqueDao.remove(estoque);
	}
}

WebContent/estoque/editar.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	template="/comuns/editar.xhtml">
<ui:define name="bodyHeader">
Editar Estoques
</ui:define>
<ui:define name="formulario">
<h:form class="box column">
<h:outputLabel class="title" value="Cadastro" />
<h:outputLabel class="label">Id:</h:outputLabel><h:inputText class="input" value="#{estoqueBean.estoque.id}" />
<h:outputLabel class="label">Empresa:</h:outputLabel>
<span class="select">
<h:selectOneMenu label="estoque" value="#{estoqueBean.estoque.empresa}" converter="entityConverter">
	<f:selectItems value="#{empresaBean.empresas}" var="empresa" itemValue="#{empresa}" itemLabel="#{empresa.nomeFantasia}" ></f:selectItems>
</h:selectOneMenu>
</span>
<h:commandButton class="button is-success is-medium" value="Salvar" action="#{estoqueBean.salva(estoqueBean.estoque)}" />
</h:form>
</ui:define>
</ui:composition>

WebContent/estoque/listar.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	template="/comuns/listar.xhtml">
<ui:define name="bodyHeader">
Simples Estoques
</ui:define>
<ui:define name="dataTable">
<h:form>
<h:commandButton class="button is-primary is-medium" value="Novo" action="#{estoqueBean.criar}"/>
</h:form>
<h:dataTable class="table" value="#{estoqueBean.estoques}" var="estoque">
<h:column>
<f:facet name="header">Id</f:facet>
#{estoque.id}
</h:column>
<h:column>
<f:facet name="header">Empresa</f:facet>
#{estoque.empresa.nomeFantasia}
</h:column>
<h:column>
<f:facet name="header">Actions</f:facet>
<h:form>
<h:commandButton class="button is-warning is-small" value="Editar" action="#{estoqueBean.editar(estoque)}" />
<h:commandButton class="button is-danger is-small" value="Excluir" action="#{estoqueBean.excluir(estoque)}" />
</h:form>
</h:column>
</h:dataTable>
</ui:define>
<ui:define name="formulario">
<h:form class="box column">
<h:outputLabel class="title" value="Cadastro" />
<h:outputLabel class="label">Id:</h:outputLabel><h:inputText class="input" value="#{estoqueBean.estoque.id}" />
<h:outputLabel class="label">Empresa:</h:outputLabel>
<span class="select">
<h:selectOneMenu label="estoque" value="#{estoqueBean.estoque.empresa}" converter="entityConverter">
	<f:selectItems value="#{empresaBean.empresas}" var="empresa" itemValue="#{empresa}" itemLabel="#{empresa.nomeFantasia}" ></f:selectItems>
</h:selectOneMenu>
</span>
<h:commandButton class="button is-success is-medium" value="Salvar" action="#{estoqueBean.salva(estoqueBean.estoque)}" />
</h:form>
</ui:define>
</ui:composition>