src/br/org/catolicasc/simples_pedidos/controller/EmpresaBean.java
package br.org.catolicasc.simples_pedidos.controller;

import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

import br.org.catolicasc.simples_pedidos.dao.EmpresaDao;
import br.org.catolicasc.simples_pedidos.entity.Empresa;

@ManagedBean
@ViewScoped
public class EmpresaBean {

	private EmpresaDao empresaDao = new EmpresaDao();
	private Empresa empresa = new Empresa();

	public void salva(Empresa empresa){
		empresaDao.salva(empresa);
		FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Empresa salvo"));
		this.empresa = new Empresa();
	}
	
	public Empresa getEmpresa(){
		return this.empresa;
	}
	
    public List<Empresa> getEmpresas(){
    	return empresaDao.listaTodos();
    }
	
	public void excluir(Empresa empresa){
		this.empresaDao.remove(empresa);
	}

	public void editar(Empresa empresa){
		this.empresa = empresa;
	}
	
	public void criar(){
		this.empresa = new Empresa();
	}
	
}

src/br/org/catolicasc/simples_pedidos/controller/UsuarioBean.java
package br.org.catolicasc.simples_pedidos.controller;

import java.io.Serializable;
import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

import br.org.catolicasc.simples_pedidos.dao.UsuarioDao;
import br.org.catolicasc.simples_pedidos.entity.Usuario;

@ManagedBean
@ViewScoped
public class UsuarioBean implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7058051429682573225L;
	
	private UsuarioDao usuarioDao = new UsuarioDao();
	private Usuario usuario = new Usuario();
	
	public void salva(Usuario usuario){
		usuarioDao.salva(usuario);
		FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Usuário cadastrado com sucesso!"));
		this.usuario = new Usuario();
	}
	
	public Usuario getUsuario(){
		return usuario;
	}
	
    public List<Usuario> getUsuarios(){
    	return this.usuarioDao.listaTodos();
    }
	
	public void excluir(Usuario usuario){
		this.usuarioDao.remove(usuario);
	}

	public void editar(Usuario usuario){
		this.usuario = usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}
	
}

WebContent/empresa/editar.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	template="/comuns/editar.xhtml">
<ui:define name="bodyHeader">
Editar Empresas
</ui:define>
<ui:define name="formulario">
<h:form class="box column">
<h:outputLabel class="title" value="Cadastro" />
<h:outputLabel class="label">Id:</h:outputLabel><h:inputText class="input" value="#{empresaBean.empresa.id}" />
<h:outputLabel class="label">Pertence á: </h:outputLabel>
<span class="checkbox">
<h:selectManyCheckbox label="empresa" value="#{empresaBean.empresa.usuarios}" converter="entityConverter">
	<f:selectItems value="#{usuarioBean.usuarios}" var="usuario" itemValue="#{usuario}" itemLabel="#{usuario.nome}"></f:selectItems>
</h:selectManyCheckbox>
</span>
<h:outputLabel class="label">Nome Fantasia:</h:outputLabel><h:inputText class="input" value="#{empresaBean.empresa.nomeFantasia}" />
<h:outputLabel class="label">Razão Social:</h:outputLabel><h:inputText class="input" value="#{empresaBean.empresa.razaoSocial}" />
<h:outputLabel class="label">CPF/CNPJ: </h:outputLabel><h:inputText class="input" value="#{empresaBean.empresa.cnpj}" />
<h:outputLabel class="label">Endereço: </h:outputLabel><h:inputText class="input" value="#{empresaBean.empresa.endereco}" />
<h:outputLabel class="label">CEP: </h:outputLabel><h:inputText class="input" value="#{empresaBean.empresa.telefone}" />

<h:commandButton class="button is-success is-medium" value="Salvar" action="#{empresaBean.salva(empresaBean.empresa)}" />
</h:form>
</ui:define>
</ui:composition>

WebContent/empresa/listar.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	template="/comuns/listar.xhtml">
<ui:define name="bodyHeader">
Simples Empresas
</ui:define>
<ui:define name="dataTable">
<h:form>
<h:commandButton class="button is-primary is-medium" value="Novo" action="#{empresaBean.criar}"/>
</h:form>
<h:dataTable class="table" value="#{empresaBean.empresas}" var="empresa" >
<h:column>
<f:facet name="header">Id</f:facet>
#{empresa.id}
</h:column>
<h:column>
<f:facet name="header">Razão Social</f:facet>
#{empresa.razaoSocial}
</h:column>
<h:column>
<f:facet name="header">CNPJ</f:facet>
#{empresa.cnpj}
</h:column>
<h:column>
<f:facet name="header">Nome Fantasia</f:facet>
#{empresa.nomeFantasia}
</h:column>
<h:column>
<f:facet name="header">Endereço</f:facet>
#{empresa.endereco}
</h:column>
<h:column>
<f:facet name="header">Telefone</f:facet>
#{empresa.telefone}
</h:column>
<h:column>
<f:facet name="header">Actions</f:facet>
<h:form>
<h:commandButton class="button is-warning is-small" value="Editar" action="#{empresaBean.editar(empresa)}" />
<h:commandButton class="button is-danger is-small" value="Excluir" action="#{empresaBean.excluir(empresa)}" />
</h:form>
</h:column>
</h:dataTable>
</ui:define>
<ui:define name="formulario">
<h:form class="box column">
<h:outputLabel class="title" value="Cadastro" />
<h:outputLabel class="label">Id:</h:outputLabel><h:inputText class="input" value="#{empresaBean.empresa.id}" />
<h:outputLabel class="label">Pertence á: </h:outputLabel>
<span class="checkbox">
<h:selectManyCheckbox label="empresa" value="#{empresaBean.empresa.usuarios}" converter="entityConverter">
	<f:selectItems value="#{usuarioBean.usuarios}" var="usuario" itemValue="#{usuario}" itemLabel="#{usuario.nome}"></f:selectItems>
</h:selectManyCheckbox>
</span>
<h:outputLabel class="label">Nome Fantasia:</h:outputLabel><h:inputText class="input" value="#{empresaBean.empresa.nomeFantasia}" />
<h:outputLabel class="label">Razão Social:</h:outputLabel><h:inputText class="input" value="#{empresaBean.empresa.razaoSocial}" />
<h:outputLabel class="label">CPF/CNPJ: </h:outputLabel><h:inputText class="input" value="#{empresaBean.empresa.cnpj}" />
<h:outputLabel class="label">Endereço: </h:outputLabel><h:inputText class="input" value="#{empresaBean.empresa.endereco}" />
<h:outputLabel class="label">Telefone: </h:outputLabel><h:inputText class="input" value="#{empresaBean.empresa.telefone}" />

<h:commandButton class="button is-success is-medium" value="Salvar" action="#{empresaBean.salva(empresaBean.empresa)}" />
</h:form>
</ui:define>
</ui:composition>