src/br/org/catolicasc/simples_pedidos/controller/ClienteBean.java
package br.org.catolicasc.simples_pedidos.controller;

import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

import br.org.catolicasc.simples_pedidos.dao.ClienteDao;
import br.org.catolicasc.simples_pedidos.entity.Cliente;

@ManagedBean
@ViewScoped
public class ClienteBean {
	
	private ClienteDao clienteDao = new ClienteDao();
	private Cliente cliente = new Cliente();

	public void salva(Cliente cliente){
		clienteDao.salva(cliente);
		FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Cliente salvo"));
		this.cliente = new Cliente();
	}
	
	public void editar(Cliente cliente) {
		this.setCliente(cliente);
	}
	
	public void criar() {
		this.cliente = new Cliente();
	}
	
	
	public Cliente getCliente(){
		return this.cliente;
	}
	
	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public List<Cliente> getClientes(){
		return this.clienteDao.listaTodos();
	}
	
	public void excluir(Cliente cliente){
		this.clienteDao.remove(cliente);
	}
}

src/br/org/catolicasc/simples_pedidos/controller/PedidoBean.java
package br.org.catolicasc.simples_pedidos.controller;

import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

import br.org.catolicasc.simples_pedidos.dao.PedidoDao;
import br.org.catolicasc.simples_pedidos.entity.Pedido;

@ManagedBean
@ViewScoped
public class PedidoBean {
	private PedidoDao pedidoDao = new PedidoDao();
	private Pedido pedido = new Pedido();

	public Pedido getPedido() {
		return this.pedido;
	}

	public void setPedido(Pedido pedido) {
		this.pedido = pedido;
	}

	public List<Pedido> getPedidos() {
		return this.pedidoDao.listaTodos();
	}

	public void criar() {
		this.pedido = new Pedido();
	}

	public void editar(Pedido pedido) {
		this.setPedido(pedido);
	}

	public void salva(Pedido pedido) {
		FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Pedido salvo"));
		pedidoDao.salva(pedido);
	}

}

WebContent/pedido/editar.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core" template="/comuns/editar.xhtml">
	<link rel="StyleSheet" type="text/css"
		href="/web/faces/css/drop-down.css" media="screen"></link>


	<h:outputScript name="myfile.js" library="css"></h:outputScript>
	<ui:define name="bodyHeader">
Editar Pedido
</ui:define>
	<ui:define name="formulario">
		<h:form class="box column">
			<h:outputLabel class="title" value="Cadastro" />
			<h:outputLabel class="label">Id:</h:outputLabel>
			<h:inputText class="input" value="#{pedidoBean.pedido.id}" />
			<h:outputLabel class="label">Cliente: </h:outputLabel>
			<span class="select">
			 <h:selectOneMenu label="pedido"
					value="#{pedidoBean.pedido.cliente}" converter="entityConverter">
					<f:selectItems value="#{clienteBean.clientes}" var="cliente"
						itemValue="#{cliente}" itemLabel="#{cliente.nome}">
					</f:selectItems>
				</h:selectOneMenu>
			</span>
			<h:outputLabel class="label">Data: </h:outputLabel>
			<h:inputText class="input" value="#{pedidoBean.pedido.data}"
				converter="DateConverter" />



			<h:messages class="message is-danger error" id="todasMensagens" />

				<span class="select">
					<h:selectOneMenu value="#{itemPedidoBean.itemPedido.itemEstoque}">
						<f:selectItem itemlLabel="-- Selecione -- "
							noSelectionOption="true" />
						<f:selectItems value="#{itemPedidoBean.itens}" var="item"
							itemvalue="#{item}" itemLabel="#{item.produto.descricao}" />
					</h:selectOneMenu>
				</span>
				<h:commandButton class="button is-success is-medium" value="Salvar"
				action="#{pedidoBean.salva(pedidoBean.pedido)}" />
		</h:form>
	</ui:define>
</ui:composition>

WebContent/pedido/listar.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core" template="/comuns/listar.xhtml">
	<ui:define name="bodyHeader">
Simples Pedidos
</ui:define>
	<ui:define name="dataTable">
		<h:form>
			<h:commandButton class="button is-primary is-medium" value="Novo"
				action="#{pedidoBean.criar}" />
		</h:form>
		<h:dataTable class="table" value="#{pedidoBean.pedidos}" var="pedido">
			<h:column>
				<f:facet name="header">Id</f:facet>
#{pedido.id}
</h:column>
			<h:column>
				<f:facet name="header">Cliente</f:facet>
#{pedido.cliente.nome}
</h:column>
			<h:column>
				<f:facet name="header">Data</f:facet>
#{pedido.data}
</h:column>
			<h:column>
				<f:facet name="header">Actions</f:facet>
				<h:form>
					<h:commandButton class="button is-warning is-small" value="Editar"
						action="#{pedidoBean.editar(pedido)}" />
					<h:commandButton class="button is-danger is-small" value="Excluir"
						action="#{pedidoBean.excluir(pedido)}" />
				</h:form>
			</h:column>
		</h:dataTable>
	</ui:define>
		<ui:define name="formulario">
		<h:form class="box column">
			<h:outputLabel class="title" value="Cadastro" />
			<h:outputLabel class="label">Id:</h:outputLabel>
			<h:inputText class="input" value="#{pedidoBean.pedido.id}" />
			<h:outputLabel class="label">Cliente: </h:outputLabel>
			<span class="select">
			 <h:selectOneMenu label="pedido"
					value="#{pedidoBean.pedido.cliente}" converter="entityConverter">
					<f:selectItems value="#{clienteBean.clientes}" var="cliente"
						itemValue="#{cliente}" itemLabel="#{cliente.nome}">
					</f:selectItems>
				</h:selectOneMenu>
			</span>
			<h:outputLabel class="label">Data: </h:outputLabel>
			<h:inputText class="input" value="#{pedidoBean.pedido.data}"
				converter="DateConverter" />

			<h:commandButton class="button is-success is-medium" value="Salvar"
				action="#{pedidoBean.salva(pedidoBean.pedido)}" />

		</h:form>

	</ui:define>
</ui:composition>