src/br/org/catolicasc/simples_pedidos/controller/EstoqueBean.java
package br.org.catolicasc.simples_pedidos.controller;

import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

import br.org.catolicasc.simples_pedidos.dao.EstoqueDao;
import br.org.catolicasc.simples_pedidos.entity.Estoque;

@ManagedBean
@ViewScoped
public class EstoqueBean {
	
	private EstoqueDao estoqueDao = new EstoqueDao();
	private Estoque estoque = new Estoque();
	
	public void salva(Estoque estoque){
		estoqueDao.salva(estoque);
		FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Estoque salvo"));
		this.estoque = new Estoque();
	}
	
	public void editar(Estoque estoque) {
		this.estoque = estoque;
	}
	
	public void criar(){
		this.estoque = new Estoque();
	}
	
	public Estoque getEstoque(){
		return this.estoque;
	}
	
	public List<Estoque> getEstoques(){
		return estoqueDao.listaTodos();
	}
	
	public void excluir(Estoque estoque){
		this.estoqueDao.remove(estoque);
	}
}

src/br/org/catolicasc/simples_pedidos/controller/ItemEstoqueBean.java
package br.org.catolicasc.simples_pedidos.controller;

import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

import br.org.catolicasc.simples_pedidos.dao.ItemEstoqueDao;
import br.org.catolicasc.simples_pedidos.entity.ItemEstoque;

@ManagedBean
@ViewScoped
public class ItemEstoqueBean {

	private ItemEstoqueDao itemEstoqueDao = new ItemEstoqueDao();
	private ItemEstoque itemEstoque = new ItemEstoque();

	public void salva(ItemEstoque itemEstoque) {
		itemEstoqueDao.salva(itemEstoque);
		FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("itemEstoque salvo"));
		this.itemEstoque = new ItemEstoque();
	}

	public void editar(ItemEstoque itemEstoque) {
		this.itemEstoque = itemEstoque;
	}

	public ItemEstoque getItemEstoque() {
		return this.itemEstoque;
	}

	public void excluir(ItemEstoque estoque) {
		this.itemEstoqueDao.remove(estoque);
	}

	public List<ItemEstoque> getItensEstoques() {
		return itemEstoqueDao.listaTodos();
	}

	public void criar() {
		itemEstoque = new ItemEstoque();
	}
}

src/br/org/catolicasc/simples_pedidos/controller/ItemPedidoBean.java
package br.org.catolicasc.simples_pedidos.controller;

import java.util.ArrayList;
import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

import br.org.catolicasc.simples_pedidos.dao.ItemPedidoDao;
import br.org.catolicasc.simples_pedidos.entity.ItemPedido;
import br.org.catolicasc.simples_pedidos.entity.Pedido;

@ManagedBean
@ViewScoped
public class ItemPedidoBean {
	private ItemPedido itemPedido = new ItemPedido();
	private ItemPedidoDao itemPedidoDao = new ItemPedidoDao();

	public ItemPedido getItemPedido() {
		return this.itemPedido;
	}

	public List<ItemPedido> getItensPedido() {
		return this.itemPedidoDao.listaTodos();
	}
	
	public void criar() {
		this.itemPedido = new ItemPedido();
	}

	public void setItemPedido(ItemPedido itemPedido) {
		this.itemPedido = itemPedido;
	}

	public void editar(ItemPedido itemPedido) {
		this.setItemPedido(itemPedido);
	}

	public void salva(ItemPedido itemPedido) {
		FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("ItemPedido salvo"));
		itemPedidoDao.salva(itemPedido);
	}

}

src/br/org/catolicasc/simples_pedidos/controller/PedidoBean.java
package br.org.catolicasc.simples_pedidos.controller;

import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

import br.org.catolicasc.simples_pedidos.dao.PedidoDao;
import br.org.catolicasc.simples_pedidos.entity.Pedido;

@ManagedBean
@ViewScoped
public class PedidoBean {
	private PedidoDao pedidoDao = new PedidoDao();
	private Pedido pedido = new Pedido();

	public Pedido getPedido() {
		return this.pedido;
	}

	public void setPedido(Pedido pedido) {
		this.pedido = pedido;
	}

	public List<Pedido> getPedidos() {
		return this.pedidoDao.listaTodos();
	}

	public void criar() {
		this.pedido = new Pedido();
	}

	public void editar(Pedido pedido) {
		this.setPedido(pedido);
	}

	public void salva(Pedido pedido) {
		FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Pedido salvo"));
		pedidoDao.salva(pedido);
	}

}

src/br/org/catolicasc/simples_pedidos/controller/ProdutoBean.java
package br.org.catolicasc.simples_pedidos.controller;

import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

import br.org.catolicasc.simples_pedidos.dao.ProdutoDao;
import br.org.catolicasc.simples_pedidos.entity.Produto;

@ManagedBean
@ViewScoped
public class ProdutoBean {

	private ProdutoDao produtoDao = new ProdutoDao();
	private Produto produto = new Produto();

	public void salva(Produto produto) {
		produtoDao.salva(produto);
		this.produto = new Produto();
	}

	public void editar(Produto produto) {
		this.produto = produto;
	}

	public Produto getProduto() {
		return this.produto;
	}

	public List<Produto> getProdutos() {
		return this.produtoDao.listaTodos();
	}

	public void excluir(Produto produto) {
		this.produtoDao.remove(produto);
	}

	public void criar() {
		this.produto = new Produto();
	}
}

WebContent/itemPedido/editar.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	template="/comuns/editar.xhtml">
<ui:define name="bodyHeader">
Editar Item de Estoque
</ui:define>
<ui:define name="formulario">
<h:form class="box column">
<h:outputLabel class="title" value="Cadastro" />
<h:outputLabel class="label">Id:</h:outputLabel><h:inputText class="input" value="#{itemEstoqueBean.itemEstoque.id}" />
<h:outputLabel class="label">Empresa:</h:outputLabel>
<span class="select">
<h:selectOneMenu label="estoque" value="#{itemEstoqueBean.itemEstoque.estoque}" converter="entityConverter">
	<f:selectItems value="#{estoqueBean.estoques}" var="estoque" itemValue="#{estoque}" itemLabel="#{estoque.empresa.nomeFantasia}"></f:selectItems>
</h:selectOneMenu>
</span>
<h:outputLabel class="label">Produto:</h:outputLabel>
<span class="select">
<h:selectOneMenu label="produto" value="#{itemEstoqueBean.itemEstoque.produto}" converter="entityConverter">
	<f:selectItems value="#{produtoBean.produtos}" var="produto" itemValue="#{produto}" itemLabel="#{produto.descricao}"></f:selectItems>
</h:selectOneMenu>
</span>
<h:outputLabel class="label">Quantidade:</h:outputLabel><h:inputText class="input" value="#{itemEstoqueBean.itemEstoque.quantidade}" />
<h:outputLabel class="label">Preço: </h:outputLabel><h:inputText class="input" value="#{itemEstoqueBean.itemEstoque.produto}" />
<h:commandButton class="button is-success is-medium" value="Salvar" action="#{empresaBean.salva(empresaBean.empresa)}" />
</h:form>
</ui:define>
</ui:composition>

WebContent/itemPedido/listar.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	template="/comuns/listar.xhtml">
<ui:define name="bodyHeader">
Simples Itens de Pedido
</ui:define>
<ui:define name="dataTable">
<h:form>
<h:commandButton class="button is-primary is-medium" value="Novo" action="#{itemPedidoBean.criar}"/>
</h:form>
<h:dataTable class="table" value="#{itemPedidoBean.itensPedido}" var="itemPedido">
<h:column>
<f:facet name="header">Id</f:facet>
#{itemPedido.id}
</h:column>
<h:column>
<f:facet name="header">Preço Unidade</f:facet>
#{itemPedido.itemEstoque.produto.preco}
</h:column>
<h:column>
<f:facet name="header">Quantidade</f:facet>
#{itemPedido.quantidade}
</h:column>
<h:column>
<f:facet name="header">Total Preço</f:facet>
#{itemPedido.precoTotal}
</h:column>
<h:column>
<f:facet name="header">Empresa:</f:facet>
#{itemPedido.itemEstoque.estoque.empresa.nomeFantasia}
</h:column>
<h:column>
<f:facet name="header">Actions</f:facet>
<h:form>
<h:commandButton class="button is-warning is-small" value="Editar" action="#{itemPedidoBean.editar(itemPedido)}" />
<h:commandButton class="button is-danger is-small" value="Excluir" action="#{itemPedidoBean.excluir(itemPedido)}" />
</h:form>
</h:column>
</h:dataTable>

</ui:define>
<ui:define name="formulario">
<h:form class="box column">
<h:outputLabel class="title" value="Cadastro" />
<h:outputLabel class="label">Id:</h:outputLabel><h:inputText class="input" value="#{itemPedidoBean.itemPedido.id}" />
<h:outputLabel class="label">Pedido:</h:outputLabel>
<span class="select">
<h:selectOneMenu label="pedido" value="#{itemPedidoBean.itemPedido.pedido}" converter="entityConverter">
	<f:selectItems value="#{pedidoBean.pedidos}" var="pedido" itemValue="#{pedido}" itemLabel="#{pedido.id}"></f:selectItems>
</h:selectOneMenu>
</span>
<h:outputLabel class="label">Produto em Estoque:</h:outputLabel>
<span class="select">
<h:selectOneMenu label="produto" value="#{itemPedidoBean.itemPedido.itemEstoque}" converter="entityConverter">
	<f:selectItems value="#{itemEstoqueBean.itensEstoques}" var="itemEstoque" itemValue="#{itemEstoque}" itemLabel="#{itemEstoque.produto.descricao}"></f:selectItems>
</h:selectOneMenu>
</span>
<h:outputLabel class="label">Quantidade:</h:outputLabel><h:inputText class="input" value="#{itemPedidoBean.itemPedido.quantidade}" />
<h:commandButton class="button is-success is-medium" value="Salvar" action="#{itemPedidoBean.salva(itemPedidoBean.itemPedido)}" />
</h:form>
</ui:define>
</ui:composition>